apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  imagePullSecrets:
  - name: docker-hub
  containers:
  - name: webapp
    image: bh7cw/webapp:latest
    envFrom:
    - configMapRef:
        name: db-config
    - secretRef:
        name: db-secret
    readinessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 45
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /v1/helloworld
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080